language: python
install:
  - pip install tox
script:
  - tox
notifications:
  slack:
    rooms:
      secure: nrW/1B0fZe2NwnFJ/o14EOlEnDU8+jWYZFbXFgFQ4hRDBgCyDyWyYfXE1PlXqtIIO/BMI3j+gkjYBunm+tpXsBBheJD9qgQYydfqK8/9GBUdeTf7CaSIk+6dcPaLH5VKsSfIC9CpF3BLbpz/UTd5UWzrk34P1tLXuuUBeBq5iD6cwuzt9IDvaSlQ99WWsVO3yG0HCLfFKUmw3Ht/AWdCcHgZEUBwbo9QMIOdv5vmQeqKwAEB6dv2eibC/tof5/ZZPAVqF8Pl+7CgAxgHeOikBGH/pvU9HshQl1281PIGeLXGmngm1807+xHhzh2xDt37NmHQfPWC0Le8pqrQAaDsoP+LCp50BBc5xiBJnx2H+Y//jf5CHCIAyPY6XWxynNAkwCCQJVWMSZwD9CUM+Wk3D7jXPcq6laKIfsDLWursihq9blTXTjDV2sXlwaDESyQxQ2yxY2h/n+Dr+wqZqXPYCUV3aVw+htm7Qz0hok8btx30Rp9ydt+KqTpiD5VsgiOnU0lKmscmXjbWAjW6TnNjMm5YUZlvGJuySpQPJgB4QtWKZaOj1XmvMSEeDeqPfSWAiOBFKOj/5SqPZ8+p2uf/xUpYYW6STByYka6o7AC31lSID2yEV/9eA/K/CyjELtb9uPlF7u88JF6+GfZd2gBBoeApKUWHH4DaZe4eNHQ9kI4=
    on_start: always
    on_failure: always
    on_success: always
