language: python
install:
  - pip install tox
script:
  - tox
notifications:
  slack:
    rooms:
      secure: UMm2dzt3BvbEd4yAqHhtNmL9sRViOTbJaaw0Bt+v9OP0cadQQm/xLIgN8HGovbTozIitor7zTvPhJh3jxe5KIN9+ymsRa0vdRSym/zJYtQv6hMThUdPwzX0P1uYJokK0Pp0bSlZ6vDFiAmiACaePXF7zkrzH2OySK74mXWeX1cIDX7jaPbx9PGQcVPo38Aqoqbsktbh3qCQuBAZm/0wGk519QJRgadbQDwLzqJerL53caqTCKBgubW5U2Rfl9j4IQTDV2mZ3dlzhVcOaQ7fP5aFfizMGv3e+f7/1vlFhrl1L+eQ5z+0Bur7Y7whbVvH+7olA8VTe72CQ4G/CoRzS9zh0mhqnVcYEjGHwfV1lANs1G7eZlQO/Ry1nzhQsVuBFpa58Jhhrr3gmCcT5kPZkRksfjYiacO5S8QKnHaMhFFsM05h1E19qkdr349qo+Wa/gh7OKEsYTzPKSUUDTILIj65UMUI2hGm8bf+RhHf9f3gO13jkb2nmSH1ajxm4i4L/nquHNPnCTvo863QuA2xhjk4vfCrIM/GOCaRPUNBrfwNXY7HwX9t9Zlf1i067zfUo1THY7EpHNPAZ/gzAJLL4vXWT87vQk3PH6bGcV2wfXf6AprIJZInaHoq2ZcK5ZgYLl+Ns8Hp2GXCKNJE/3KKFtE4PBAB4U+tZp+CMkRIJts4=
    on_start: always
    on_failure: always
    on_success: always
